image: archlinux
packages:
  - rustup
  - postgresql
  - postgresql-libs
sources:
  - https://git.sr.ht/~hidrile/heiwa-authors
tasks:
  - setup: |
      rustup default stable
      rustup component add clippy
  - build: |
      cd heiwa-authors
      cargo build --release
  - tests: |
      postgres -D /usr/local/pgsql/data >logfile 2>&1 &
      cd heiwa-authors
      cargo fmt -- --check
      cargo clippy -- -D warnings
      cargo test
