image: archlinux
packages:
  - rustup
sources:
  - https://git.sr.ht/~hidrile/heiwa-authors
tasks:
  - setup: |
      rustup default stable
      rustup component add clippy
  - build: |
      cd heiwa-authors
      cargo build --release
  - tests: |
      cd heiwa-authors
      cargo fmt -- --check
      cargo clippy -- -D warnings
      cargo test