image: "rust:latest"

build:cargo:
  script:
    - rustc --version && cargo --version
    - rustup component add rustfmt clippy
    - cargo fmt -- --check
    - cargo clippy -- -D warnings

test:junit-report:
   services:
    - postgres:latest
   variables:
     POSTGRES_PASSWORD: postgres
   script:
     - sudo apt-get update && sudo apt-get -y install libpq-dev
     - cargo install diesel_cli --no-default-features --features postgres
     - diesel setup
     - cargo install junitify
     - cargo test -- --format=json -Z unstable-options --report-time | junitify --out $CI_PROJECT_DIR/tests/
   artifacts:
     when: always
     reports:
       junit: $CI_PROJECT_DIR/tests/*.xml

#deploy:
#  stage: deploy
#  script: echo "Define your deployment script!"
#  environment: production
