matrix:
  RUST: [stable, beta, nightly]

steps:
  test:
    image: rust
    environment: [CARGO_TERM_COLOR=always]
    commands:
      - rustup default $RUST
      - rustup component add rustfmt clippy
      - cargo fmt -- --check
      - cargo check
      - cargo clippy -- -D warnings 
      - cargo test
