[package]
name = "heiwa"
license = "GPL-3.0-or-later"
repository = "https://git.sr.ht/~hidrile/heiwa-authors"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = { version = "0.12.0", features = ["with-axum"] }
askama_axum = "0.3.0"
argon2 = "0.5.0"
axum = "0.6.7"
axum-auth = "0.4.0"
axum-extra = { version = "0.7.2", features = ["cookie"] }
axum-sessions = "0.5.0"
chrono = "0.4.26"
diesel = { version = "2.1.0", features = ["postgres", "chrono"] }
dotenvy = "0.15.7"
hyper = "0.14.27"
jsonwebtoken = "8.3.0"
lazy_static = "1.4.0"
rand = "0.8.5"
reqwest = { version = "0.11.18", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
time = "0.3.23"
tokio = { version = "1.25.0", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.4.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
validator = { version = "0.16.0", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "1.3.0"
mime = "0.3.17"
