[package]
name = "heiwa-authors"
license = "GPL-3.0-or-later"
repository = "https://git.sr.ht/~hidrile/heiwa-authors"
version = "0.1.0"
edition = "2021"

[dependencies]
argon2 = "0.5.0"
axum = "0.6.7"
diesel = { version = "2.1.0", features = ["postgres", "chrono"]}
dotenvy = "0.15.7"
heiwa-common = "0.1.2"
hyper = "0.14.27"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["full"] }
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.4.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
validator = { version = "0.16.0", features = ["derive"]}

[dev-dependencies]
pretty_assertions = "1.3.0"
mime = "0.3.17"