# Example configuration for developments only
version: '3.1'
services:
  heiwa:
    build: .
    environment:
      - RUST_LOG=debug
      - SERVER_PORT=8000
      - SERVER_TIMEOUT=5
      - DATABASE_URL=postgres://postgres:postgres@db:5432/heiwa
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
  adminer:
    image: adminer
    ports:
      - "8080:8080"