# Used for local developments only
version: '3.1'
services:
  db:
    image: postgres
    ports:
      - "5001:5432"
    environment:
      POSTGRES_PASSWORD: superpassword
  adminer:
    image: adminer
    ports:
      - "8080:8080"
